#!/bin/bash

set -e

if [ -z "$npm_package_name" ]
then
    echo Deploy running \"npm run deploy:eb\"
    exit 1
fi

CHAIN=${CHAIN:-eth}
EB_APP_NAME=$npm_package_name
EB_ENV_NAME=$EB_APP_NAME-$CHAIN
EB_INSTANCE_TYPE=${EB_INSTANCE_TYPE:-m5.large}
REGION=us-east-2

echo ""
echo Deploying with configuration:
echo ""
echo CHAIN="$CHAIN"
echo EB_APP_NAME="$EB_APP_NAME"
echo EB_ENV_NAME="$EB_ENV_NAME"
echo ETH_NODE_URL="$ETH_NODE_URL"
echo EXPLORER_API_KEY="$EXPLORER_API_KEY"
echo LOGGER_CONSOLE_LEVEL="$LOGGER_CONSOLE_LEVEL"
echo LOGGER_PAPERTRAIL_HOST="$LOGGER_PAPERTRAIL_HOST"
echo LOGGER_PAPERTRAIL_PORT="$LOGGER_PAPERTRAIL_PORT"
echo REGION="$REGION"
echo SUBSCRIPTION_MAX_ADDRESSES="$SUBSCRIPTION_MAX_ADDRESSES"

if [ -z "$ETH_NODE_URL" ]
then
    echo Missing Ethereum node URL
    exit 1
fi

echo ""
echo Initializing Elastic Beanstalk

eb init "$EB_APP_NAME" \
--platform "docker" \
--region "$REGION" \
--verbose

ENVIRONMENTS=$(eb list | grep $EB_ENV_NAME | cat)
if [ -z "$ENVIRONMENTS" ]
then
    echo ""
    echo Creating Elastic Beanstalk environment "$EB_ENV_NAME"
    
    eb create "$EB_ENV_NAME" \
    --elb-type application \
    --envvars "ETH_NODE_URL=$ETH_NODE_URL,EXPLORER_API_KEY=$EXPLORER_API_KEY,LOGGER_PAPERTRAIL_HOST=$LOGGER_PAPERTRAIL_HOST,LOGGER_PAPERTRAIL_PORT=$LOGGER_PAPERTRAIL_PORT,LOGGER_PAPERTRAIL_PROGRAM=$EB_ENV_NAME" \
    --instance_type $EB_INSTANCE_TYPE \
    --tags "Product=Metronome,Service=Tx Provider,Contact=$npm_package_author_name" \
    --verbose
    
    echo Configure the load balancer and custom domain name in the the Elastic Beanstalk console...
    echo Run \"eb console "$EB_ENV_NAME"\"
else
    echo ""
    echo Deploying to Elastic Beanstalk environment "$EB_ENV_NAME"
    
    eb deploy "$EB_ENV_NAME" \
    --verbose
    
    eb setenv ETH_NODE_URL="$ETH_NODE_URL" EXPLORER_API_KEY="$EXPLORER_API_KEY" LOGGER_PAPERTRAIL_HOST="$LOGGER_PAPERTRAIL_HOST" LOGGER_PAPERTRAIL_PORT="$LOGGER_PAPERTRAIL_PORT" LOGGER_PAPERTRAIL_PROGRAM="$EB_ENV_NAME"  \
    --environment "$EB_ENV_NAME" \
    --verbose
fi
